services:
  postgres:
    image: postgres:16
    container_name: deepline-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: deepline-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      TZ: Asia/Seoul
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: >
      bash -lc "
        rabbitmq-plugins enable --offline rabbitmq_stomp &&
        rabbitmq-server
      "
    networks:
      - app-network

  backend:
    image: deepline-backend:latest
    container_name: deepline-backend
    restart: always
    build:
      context: ./deepline-backend
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/app/config/application.yml:ro
      - ./uploads:/app/uploads
    environment:
      TZ: Asia/Seoul
      SPRING_CONFIG_LOCATION: file:/app/config/application.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://deepline-postgres:5432/deepline_db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  frontend:
    image: deepline-frontend:latest
    container_name: deepline-frontend
    restart: always
    build:
      context: ./deepline-frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    env_file:
      - ./.env
    environment:
      TZ: Asia/Seoul
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: deepline-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    environment:
      TZ: Asia/Seoul
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: deepline-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Seoul
    depends_on:
      - prometheus
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: deepline-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Seoul
    volumes:
      - /data/redis/data:/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
